[ch8]
cases = [
    "ch8_usertest",
    "ch8b_usertest",
    "ch8_deadlock_mutex1",
    "ch8_deadlock_sem1",
    "ch8_deadlock_sem2",
    "threads",
    "threads_arg",
    "sync_sem",
    "mpsc_sem",
    "test_condvar",
]

[ch8_exercise]
cases = [
    "ch8_usertest",
    "ch8b_usertest",
    "ch8_deadlock_mutex1",
    "ch8_deadlock_sem1",
    "ch8_deadlock_sem2",
    "threads",
    "threads_arg",
    "sync_sem",
    "mpsc_sem",
    "test_condvar",
    "sync_experiment",
]
